window.PROJECTS = [
  {
    id: "morningafter",
    title: "MorningAfter",
    eyebrow: "FLAGSHIP · INDEPENDENT PRODUCT",
    year: "2026",
    tone: "red",
    category: "featured",
    tagline: "A wake-aware approach to digital wellbeing.",
    summary: "A native Android digital-wellbeing app that detects morning wake events and temporarily restricts distracting apps.",
    why: "I kept getting distracted by my phone immediately after waking up. Existing blockers were either too manual, too easy to bypass, or not built around the specific moment I cared about: the first part of the morning.",
    solution: "MorningAfter watches for wake events, starts configurable lock periods, blocks selected apps, and gives me enough control to make the restriction useful without turning my phone into a brick.",
    details: [
      "Wake detection using Samsung Health sleep data",
      "Accessibility Service-based app blocking",
      "Configurable lock durations, app groups, allowlists, and fallback behavior",
      "Persistent background monitoring and state restoration",
      "Strict-lock behavior designed to reduce obvious bypass routes",
      "Multi-category lock system with independent durations and labels"
    ],
    lessons: "The difficult part wasn’t making one screen that says ‘blocked.’ It was state, lifecycle behavior, UX around permissions, background reliability, and deciding how strict the product should be without becoming hostile to the user.",
    stack: ["Kotlin", "Android", "Samsung Health", "Accessibility Service", "AdMob"],
    statA: "Native Android",
    statB: "Wake-aware locking"
  },
  {
    id: "gmailcalendar",
    title: "Gmail to Calendar",
    eyebrow: "AUTOMATION · INDEPENDENT PROJECT",
    year: "2024–2025",
    tone: "blue",
    category: "work",
    tagline: "Turning unstructured email into structured calendar events.",
    summary: "An automated pipeline that reads email, extracts events with Gemini, creates Calendar entries, deduplicates them, and sends notifications.",
    why: "Important events kept arriving as unstructured email text, while manually transferring dates, times, locations, and titles into Google Calendar was repetitive and error-prone.",
    solution: "A Google Apps Script workflow processes incoming mail, asks Gemini for structured event data, validates the result, creates Calendar events, and notifies me through Pushbullet.",
    details: [
      "Structured extraction of event name, date, time, location, and duration",
      "Relative-date handling for phrases like ‘tomorrow’ and ‘Friday’",
      "Gemini API integration through Google Apps Script",
      "Google Calendar event creation and event-link generation",
      "Pushbullet notifications",
      "Hash-based deduplication to prevent duplicate event creation"
    ],
    lessons: "Automation becomes a real system the moment it touches messy human language. The project pushed me to think about ambiguity, malformed model output, duplicate detection, time handling, and what should happen when an email only partially describes an event.",
    stack: ["JavaScript", "Google Apps Script", "Gemini API", "Gmail", "Google Calendar", "Pushbullet"],
    statA: "1-minute polling",
    statB: "End-to-end automation"
  },
  {
    id: "youtubedownloader",
    title: "YouTube Downloader",
    eyebrow: "DESKTOP TOOL · INDEPENDENT PROJECT",
    year: "2026",
    tone: "yellow",
    category: "work",
    tagline: "A focused desktop tool for a workflow I wanted to simplify.",
    summary: "A Python desktop app for downloading YouTube videos or audio with a simple GUI, multi-URL support, live progress, and clipboard detection.",
    why: "I kept needing video and audio assets from YouTube, but I didn’t want to rely on sketchy download sites that kept going offline and forcing me to find another one that worked. I built a dependable desktop tool so I could handle that workflow myself.",
    solution: "A Tkinter interface wraps yt-dlp, accepts batches of URLs, auto-detects YouTube links from the clipboard, downloads MP3 or MP4 output, and streams progress back into the UI without freezing it.",
    details: [
      "Batch downloading for multiple URLs",
      "MP3 and MP4 output modes through yt-dlp",
      "Clipboard detection and automatic URL insertion",
      "Background-threaded downloads to keep the interface responsive",
      "Live subprocess output and progress reporting",
      "Cross-platform downloads-folder launching"
    ],
    lessons: "This is one of my favorite kinds of project: small enough to finish quickly, specific enough to genuinely improve my day, and polished enough that I kept using the thing instead of going back to the old workflow.",
    stack: ["Python", "Tkinter", "yt-dlp", "Threading", "Subprocess"],
    statA: "Desktop GUI",
    statB: "Built for my own workflow"
  },
  {
    id: "frognition",
    title: "Frognition",
    eyebrow: "TEAM SOFTWARE ENGINEERING PROJECT",
    year: "2025",
    tone: "green",
    category: "work",
    tagline: "A full-stack educational math game built by a four-person team.",
    video: "frognition.mp4",
    summary: "A web-based educational math game built in a four-person Agile team using React and Django REST Framework.",
    why: "The project started as a software-engineering course team project, but it grew into a full playable concept: a frog moves through themed math worlds, eats the bug with the correct answer, races the clock, and earns stars based on performance.",
    solution: "The team split frontend, backend, authentication, audio, dashboard, gameplay, and reporting work across iterative sprints. My work included core gameplay systems such as the level timer, level-start flow, and star/results screen.",
    details: [
      "React frontend with Django REST Framework backend",
      "Timed math gameplay and performance-based star results",
      "Multiple problem types and themed areas",
      "REST API integration for gameplay state and reporting",
      "Git-based collaboration and sprint planning",
      "Presented as a student showcase project"
    ],
    lessons: "Frognition was where software stopped being only about whether my own code worked. It forced me to care about interfaces between people, components, APIs, task ownership, merge conflicts, deadlines, and communicating enough that four separate pieces could become one application.",
    stack: ["React", "JavaScript", "Django", "Django REST Framework", "Git", "Agile"],
    statA: "4-person team",
    statB: "Full-stack web app"
  },
  {
    id: "snake3",
    title: "Snake 3",
    eyebrow: "GAME · INDEPENDENT PROJECT",
    year: "2025",
    tone: "purple",
    category: "work",
    tagline: "Expanding a familiar game into a complete, published project.",
    url: "https://realadriamo.itch.io/snake3",
    urlLabel: "Play Snake 3 on itch.io",
    summary: "A Pygame project that turns classic Snake into a more complete game with its own identity, systems, and release-ready presentation.",
    why: "Snake 3 began as a personal game-development project and became an opportunity to work through the systems, polish, and iteration required to turn a simple concept into a complete playable release.",
    solution: "I built the gameplay loop in Python with Pygame, iterated on presentation and mechanics, and published the finished result on itch.io.",
    details: [
      "Real-time game loop and input handling",
      "Gameplay-state and collision systems",
      "Polished presentation beyond a minimal Snake clone",
      "Packaged and published as a playable project",
      "Iterative balancing and refinement"
    ],
    lessons: "Games are brutally good at exposing tiny problems. Timing, input, feedback, difficulty, and visual clarity all become obvious immediately because the user is interacting with the system every fraction of a second.",
    stack: ["Python", "Pygame", "Game Design"],
    statA: "Published",
    statB: "Real-time gameplay"
  },
  {
    id: "translatetelephone",
    title: "Translate Telephone",
    eyebrow: "EXPERIMENT",
    year: "2025",
    tone: "blue",
    category: "fun",
    tagline: "An API experiment in how meaning changes across repeated translation.",
    summary: "A Python experiment that repeatedly translates text through random languages before bringing it back to English.",
    why: "I wanted a small, visible experiment for exploring translation APIs, randomized processing, and the way meaning drifts across repeated transformations.",
    solution: "The script chooses random languages, translates the text step by step through Google Cloud Translation, shows progress, records the entire language path, and eventually translates the mutated result back to English.",
    details: [
      "Google Cloud Translation API integration",
      "Randomized language routing",
      "Progress display for long translation chains",
      "Language-path tracking",
      "HTML entity cleanup in translated output"
    ],
    lessons: "Small experimental projects are a great excuse to touch an API, play with edge cases, and build something that produces immediately visible results—even if the result is linguistic damage.",
    stack: ["Python", "Google Cloud Translation", "APIs"],
    statA: "100+ languages",
    statB: "Translation experiment"
  },
  {
    id: "chipotleroulette",
    title: "Chipotle Roulette",
    eyebrow: "PROCEDURAL GENERATOR",
    year: "2025",
    tone: "orange",
    category: "fun",
    tagline: "A menu-aware procedural generator built around real constraints.",
    summary: "A Python generator that creates randomized Chipotle orders while still respecting the weird little constraints of the menu.",
    why: "I built this as a playful exercise in procedural generation: randomize an order while still respecting the structure and constraints of the menu.",
    solution: "The script randomizes entrée format, proteins, rice, beans, toppings, shells, sides, and ordering logic while accounting for menu-specific differences between burritos, bowls, tacos, quesadillas, and kids meals.",
    details: [
      "Menu-aware random generation",
      "Different logic by entrée type",
      "Ingredient ordering for readable output",
      "Conditional shells, sides, and add-ons",
      "Enough edge-case logic to make a joke project weirdly specific"
    ],
    lessons: "Even goofy generators get more interesting when the random output has rules. Constraints are what make procedural generation feel intentional instead of just noisy.",
    stack: ["Python", "Randomization", "Procedural Logic"],
    statA: "Rule-based generation",
    statB: "Menu-aware logic"
  }
];
